Repository dotrachit/gitg0, pull requests merged in 2020-11, with the labels that each got.

#12 Add dynamic username
  lib/issue.js
Labels: bug

#14 Add the .gitgo file
  .gitgo
  lib/inquirer.js
Labels: cli, enhancement

#16 Fetch Issue Labels
  lib/issue.js
Labels: cli, enhancement

#19 Write issue details in .gitgo dynamically
  .gitgo
  lib/funcs/jsonReader.js
  lib/inquirer.js
  lib/issue.js
Labels: cli, enhancement

#20 Add branch name & commit message suggestions
  lib/funcs/generate.js
Labels: cli, enhancement

#21 Add cli commands for config and startup
  bin/index.js
  index.js
  lib/funcs/generate.js
  lib/inquirer.js
  package-lock.json
  package.json
Labels: cli, command, enhancement

#25 Update gitgo properties
  .gitgo
Labels: cli, enhancement

#26 Fix release workflow
  .github/workflows/release-drafter.yml
Labels: general

#28 Write the commit type to gitgo
  lib/inquirer.js
  package.json
Labels: cli, command, enhancement

#30 cli: fixed .gitgo line change after writeFile() execution
  .gitgo
  lib/inquirer.js
  lib/issue.js
Labels: cli, enhancement

#31 cli: Check if suggested branch name exists
  .gitgo
  .gitignore
  lib/funcs/generate.js
  lib/issue.js
Labels: cli

#34 Suggest commit messages using the template provided in .gitgo file
  lib/funcs/commit-gen.js
Labels: cli

#36 Update gitgo attributes dynamically
  .gitgo
  lib/inquirer.js
Labels: bug, cli

#40 Add instructions for checking out and committing
  .gitgo
  bin/index.js
  package-lock.json
  package.json
Labels: cli, command, enhancement

#42 Fix commit message suggestion for standard template
  .gitgo
  lib/funcs/commit-gen.js
Labels: cli

#44 Change recommended text color to green
  .gitgo
  lib/inquirer.js
Labels: cli

#46 Capitalizing default value on pressing enter
  .gitgo
  lib/inquirer.js
Labels: cli, documentation

#47 Add contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#50 Added Issue Type Recommendations feature
  .gitgo
  lib/funcs/commit-gen.js
  lib/funcs/rec-iss-type.js
  lib/inquirer.js
  lib/issue.js
  package-lock.json
Labels: cli, enhancement

#49 Update Readme
  README.md
Labels: documentation

#52 Add a command to give summary of all instructions
  .gitgo
  README.md
  bin/index.js
Labels: cli, command, enhancement

#57 Test made for Commit Suggestion
  .gitgo
  bin/index.js
  lib/files.js
  lib/funcs/commit-gen.js
  lib/funcs/generate.js
  lib/funcs/jsonReader.js
  lib/funcs/rec-iss-type.js
  lib/inquirer.js
  lib/issue.js
  package-lock.json
  package.json
  test/commit-gen.test.js
Labels: test

#58 Test written for Branch name suggestion
  lib/funcs/commit-gen.js
  lib/funcs/generate.js
  tests/generate.test.js
Labels: test
